name: Brokkoli Analysis
version: "1.0.0"
slug: brokkoli_analysis
description: Image analysis addon for plant monitoring
url: https://github.com/your-username/brokkoli-analysis
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  mqtt:
    host: core-mosquitto
    port: 1883
    username: ""
    password: ""
    discovery_prefix: homeassistant
  sources:
    - type: folder
      path: /share/brokkoli/images
      update_interval: 300
  processors:
    - type: green_pixels
      enabled: true
      hsv_lower: [35, 40, 40]
      hsv_upper: [85, 255, 255]
      quadrants: false
schema:
  mqtt:
    host: str
    port: int(1,65535)
    username: str?
    password: password?
    discovery_prefix: str
  sources:
    - type: list(folder)
      path: str
      update_interval: int(30,3600)
  processors:
    - type: list(green_pixels)
      enabled: bool
      hsv_lower: [int(0,179), int(0,255), int(0,255)]
      hsv_upper: [int(0,179), int(0,255), int(0,255)]
      quadrants: bool
map:
  - share:rw
image: ghcr.io/your-username/brokkoli-analysis-{arch} 