name: Brokkoli Analysis
version: "1.0.0"
slug: brokkoli_analysis
description: "Image and video stream analysis for plant monitoring with NDVI, green pixel counting, and more"
url: "https://github.com/dingausmwald/homeassistant-brokkoli-analysis"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
options:
  mqtt:
    host: core-mosquitto
    port: 1883
    username: ""
    password: ""
    discovery_prefix: homeassistant
  sources:
    - name: "Camera Left"
      type: folder
      path: "/share/brokkoli/camera_left"
      update_interval: 30
    - name: "Camera Right"  
      type: folder
      path: "/share/brokkoli/camera_right"
      update_interval: 30
  processors:
    - name: "Green Pixels"
      type: green_pixels
      enabled: true
      quadrants: false
    - name: "NDVI"
      type: ndvi
      enabled: false
      quadrants: false
  log_level: info
schema:
  mqtt:
    host: str
    port: port
    username: str?
    password: password?
    discovery_prefix: str
  sources:
    - name: str
      type: list(folder|stream)
      path: str
      update_interval: int(5,3600)
      stream_url: url?
  processors:
    - name: str
      type: list(green_pixels|ndvi|fisheye_correction|rotation)
      enabled: bool
      quadrants: bool?
      rotation_angle: int(-360,360)?
  log_level: list(debug|info|warning|error)
ports:
  8099/tcp: 8099
map:
  - share:rw
  - config:r
image: ghcr.io/dingausmwald/homeassistant-brokkoli-analysis-{arch} 