name: Brokkoli Analysis
version: "1.0.0"
slug: brokkoli_analysis
description: "Analyze plant monitoring images with NDVI, green pixel counting, and fisheye correction"
url: "https://github.com/dingausmwald/homeassistant-brokkoli-analysis"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  mqtt:
    host: "core-mosquitto"
    port: 1883
    username: ""
    password: ""
    discovery_prefix: "homeassistant"
  image_processing:
    input_folder: "/share/brokkoli_images"
    supported_formats: ["jpg", "jpeg", "png", "bmp", "tiff"]
    process_interval: 300
    enable_quadrant_analysis: true
  sensors:
    device_name: "Brokkoli Monitor"
    device_id: "brokkoli_monitor"
schema:
  mqtt:
    host: str
    port: int(1,65535)
    username: str?
    password: password?
    discovery_prefix: str
  image_processing:
    input_folder: str
    supported_formats: [str]
    process_interval: int(10,3600)
    enable_quadrant_analysis: bool
  sensors:
    device_name: str
    device_id: str
image: "local/brokkoli-analysis" 